server:
  port: 8050

spring:
  # MySQL
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/oreuda?useUniCode=yes&characterEncoding=UTF-8
#    username: oreuda
#    password: git0410
#  servlet:
#    multipart:
#      max-file-size: 100MB
#      max-request-size: 100MB

  # JPA Properties
#  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
##    generate-ddl: true
#    hibernate:
#      ddl-auto: none
#      use-new-id-generator-mappings: false
#      jdbc:
#        time_zone: Asia/Seoul
#    open-in-view: false

  # Redis
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
#    password: git0410

# graphql
graphql:
  graphiql:
    enabled: true

