## OAuth2
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.6f160bb16c36edc5
            client-secret: 6370be4fab5c5636634dbfbe61cf86f771ca8b81
            scope: user,user:email,read:user,repo,read:org
            client-name: GitHub
            redirect-uri: "https://oreuda.kr/login/oauth2/code/{registrationId}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            provider: github

# JWT
jwt:
  header: Authorization
  secret: 6015c999199ff10b966d382494c4796244359a0a97e78be2de11b978402207f1028c2dc780185fac08dd3ef8b7c81b8e99a29130e4f3c130ef7e33c27f2a2d69
  token-validity-in-seconds: 3600