server:
  port: 9000

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
        # business-server
        - id: business-server
          uri: http://172.28.0.22:8080/
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthorizationHeaderFilter

        # data-server
        - id: data-server
          uri: http://172.28.0.24:8050/
          predicates:
            - Path=/api/v1/data/**
          filters:
            - AuthorizationHeaderFilter

        # plant-server
        - id: plant-server
          uri: http://172.28.0.25:8060/
          predicates:
            - Path=/api/v1/plant/**
          filters:
            - AuthorizationHeaderFilter

        # repo-server
        - id: repo-server
          uri: http://172.28.0.26:8070/
          predicates:
            - Path=/api/v1/folder/**, /api/v1/repository/**
          filters:
            - AuthorizationHeaderFilter

        # # auth-server
        # - id: login-server
        #   uri: http://52.79.221.133:8090/
        #   predicates:
        #     - Path=/oauth2/**

        - id: auth-server
          uri: http://172.28.0.23:8090/
          predicates:
            - Path=/api/v1/auth/**

        # test-server
        - id: test-server
          uri: http://172.28.0.22:8080/
          predicates:
            - Path=/api/v1/test/**

  # application-jwt
  profiles:
    include: jwt

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defalutZone: http://172.28.0.20:8761/eureka

