server:
  port: 9000

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
        - id: business-server
          uri: http://localhost:8080/
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthorizationHeaderFilter

        - id: test-server
          uri: http://localhost:8080/
          predicates:
            - Path=/api/v1/test/**

        - id: auth-server
          uri: http://localhost:8090/
          predicates:
            - Path=/oauth2/**

        - id: auth-server
          uri: http://localhost:8090/
          predicates:
            - Path=/api/v1/auth/**

  # application-jwt
  profiles:
    include: jwt

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defalutZone: http://localhost:8761/eureka

