
server:
  port: 8080


spring:
  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/oreuda?useUniCode=yes&characterEncoding=UTF-8
    username: oreuda
    password: 'git0410'
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # JPA Properties
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

eureka:
  instance:
    prefer-ip-address: true
    appname: business-server
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.28.0.20:8761/eureka