server:
  port: 8060

spring:
  #MySQL
  datasource:
    url: jdbc:mysql://mysql:3306/oreuda?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: oreuda
    password: 'git0410'
    driver-class-name: com.mysql.cj.jdbc.Driver
  #JPA
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      jdbc:
        time_zone: Asia/Seoul
    open-in-view: false
  #Redis
  redis:
    host: redis
    port: 6379
    password: 'git0410'

eureka:
  instance:
    prefer-ip-address: true
    appname: plant-server
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.28.0.20:8761/eureka
